---
apiVersion: v1
kind: Namespace
metadata:
  name: reliably

---
apiVersion: v1
kind: Pod
metadata:
  name: chaostoolkit
  labels:
    app: chaostoolkit
spec:
  restartPolicy: Never
  containers:
  - name: chaostoolkit
    image: chaostoolkit/chaostoolkit:latest
