version: 2.1
jobs:
  discover:
    docker:
      - image: ghcr.io/reliablyhq/cli/cli:latest
    working_directory: /home
    steps:
      - checkout # check out the code in the project directory
      - run: reliably discover /home

workflows:
  reliably:
    jobs:
      - discover
