version: 2.1
jobs:
  scan:
    docker:
      - image: ghcr.io/reliablyhq/cli/cli:latest
        environment:
          RELIABLY_TOKEN: $RELIABLY_TOKEN
    working_directory: /home
    steps:
      - checkout # check out the code in the project directory
      - run: reliably scan kubernetes .

workflows:
  reliably:
    jobs:
      - scan
