name: Reliably Actions examples
on: push

jobs:
  reliably:
    runs-on: ubuntu-latest
    env:
          RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run Reliably CLI
        uses: reliablyhq/actions@v1
        with:
          args: --version
      - name: Run Reliably CLI
        uses: reliablyhq/actions@v1
        with:
          args: --help
      - name: Run Reliably CLI
        uses: reliablyhq/actions@v1
        with:
          args: auth status

  setup-reliably:
    runs-on: ubuntu-latest
    steps:
      - uses: reliablyhq/gh-action/setup@v1
      - run: reliably --version

  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run Reliably
        uses: reliablyhq/actions/scan@v1
        env:
          RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}
        continue-on-error: true

  slo-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run Reliably
        uses: reliablyhq/actions/slo-report@v1
        env:
          RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}