name: Reliably GH workflow demo

on:
  push:
    branches:
      - main
    paths:
      - 'manifest.yaml'
      #- '**.yaml'
      #- '**.yml'

env:
  RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}

jobs:
  basic-usage:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Run Reliably'
        uses: reliablyhq/gh-action@v1
        # comment next line to fails the CI if issues are found
        continue-on-error: true

  code-scanning-usage:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Run Reliably'
        uses: reliablyhq/gh-action@v1
        continue-on-error: true
        with:
          format: "sarif"
          output: "reliably.sarif"
      - name: Display Reliably SARIF report
        run: |
          cat reliably.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reliably.sarif
